name: AutoExecutor CI

on:
  push:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      # clone the unlogged-sdk project
      - name: checkout commit
        uses: actions/checkout@v4

      # unlogged-sdk project
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get version
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # Testing script
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/test/python/requirements.txt
      - name: Run testing script
        run: |
          python3 ./src/test/python/autoexecute_ci.py ${{ env.RELEASE_VERSION }}

      - name: Store reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: AutoExecutorReports
          path: |
            **/target/test-classes/auto-test-resources/AutoExecutorReports/

      - name: Summarize Job summary - start
        if: always()
        run: |
          echo "# AutoExecutor CI results" >> $GITHUB_STEP_SUMMARY
          echo "**SDK version** : ${{ env.RELEASE_VERSION }}" >> $GITHUB_STEP_SUMMARY

      - name: Add report contents
        run: |
          cat target/test-classes/auto-test-resources/AutoExecutorReports/unlogged-spring-maven-demo-summary.md >> $GITHUB_STEP_SUMMARY
          cat target/test-classes/auto-test-resources/AutoExecutorReports/unlogged-spring-webflux-maven-demo-summary.md >> $GITHUB_STEP_SUMMARY
        if: always()

